# Generated by Django 4.0.5 on 2022-07-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_info',
            name='map_location',
            field=models.TextField(),
        ),
    ]
