# Generated by Django 4.0.5 on 2022-06-30 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetters',
            new_name='NewsLetter',
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'NewsLetters'},
        ),
    ]
