# Generated by Django 4.0.5 on 2022-06-30 01:07

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50)),
                ('Category_Image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=20)),
                ('Product_price', models.FloatField(max_length=50)),
                ('Product_Currency', models.CharField(max_length=6)),
                ('Product_Colour', multiselectfield.db.fields.MultiSelectField(choices=[('RED', 'red'), ('BLUE', 'blue'), ('ORANGE', 'orange'), ('YELLOW', 'yellow'), ('BLACK', 'black')], max_length=28)),
                ('Product_Colour_Tag', multiselectfield.db.fields.MultiSelectField(choices=[('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#FFA500', '#FFA500'), ('#FFFF00', '#FFFF00'), ('#000000', '#000000')], max_length=39)),
                ('Product_Reduction', models.CharField(max_length=4)),
                ('Product_Fixed', models.FloatField(max_length=50)),
                ('Size', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'xl'), ('XXL', 'xxl')], max_length=12)),
                ('Image', models.URLField()),
                ('New', models.BooleanField(default=False)),
                ('Sale', models.BooleanField(default=False)),
                ('Prom_Time', models.DurationField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_category', to='Shop.category')),
            ],
        ),
    ]
