# Generated by Django 4.0.5 on 2022-06-30 01:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_Colour',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('BLACK', 'Black')], max_length=28),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_Fixed',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_Reduction',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='products',
            name='Size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=12),
        ),
    ]
