# Generated by Django 4.0.5 on 2022-06-30 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_products_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
