# Generated by Django 4.0.5 on 2022-06-30 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_rename_products_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
