# Generated by Django 4.0.5 on 2022-07-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
